### ISSUE TITLE
Make context menu item conditional on an image not having an alt attribute.

### ISSUE THREAD

**Issue by yzen** [mozilla/Bubo-Eye#10]
We only want to display the menu item for the extension when an image does not have an alt attribute. We can assume, for the time being, that if the image has an alt attribute (even "") it has a name provided intentionally.

Lets find out how we can make that check happen before we render the menu item.

**Comment by hamletv** [comment]
Will this still be necessary if we're switching from passing results to the alt attribute to using aria-describedby and or aria-labelledby?
